name: 每日健康菜品推送

on:
  schedule:
    # 每个工作日（周一到周五）北京时间上午9点推送（UTC时间凌晨1点）
    - cron: '0 1 * * 1-5'
  workflow_dispatch:  # 允许手动触发

jobs:
  send-recipe:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装依赖
      run: |
        pip install --upgrade pip
        
    - name: 发送每日菜品
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python send_daily_recipe.py
